@extends('layouts.admin')

@section('title', 'Settings')

@section('content')
    <div class="min-h-screen p-4 sm:p-6 lg:p-8">

        <div class="mb-6">
            <h1 class="text-3xl sm:text-4xl font-bold text-gray-900 mb-2">Settings</h1>
            <p class="text-gray-600">Manage your company logo and official office address for documents.</p>
        </div>

        @if(session('success'))
            <div class="mb-4 p-3 rounded bg-green-50 text-green-800 border border-green-200">
                {{ session('success') }}
            </div>
        @endif

        @if($errors->any())
            <div class="mb-4 p-3 rounded bg-red-50 text-red-800 border border-red-200">
                <ul class="list-disc pl-5">
                    @foreach($errors->all() as $e)
                        <li>{{ $e }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="bg-white border border-gray-200 rounded-lg p-6 max-w-3xl">
            <form action="{{ route('backend.admin.settings.update') }}" method="POST" enctype="multipart/form-data">
                @csrf

                {{-- Logo --}}
                <div class="mb-6">
                    <label class="block font-semibold text-gray-900 mb-2">Company Logo</label>

                    <div class="flex items-center gap-4">
                        <img src="{{ $settings->logo_url }}" alt="Company Logo"
                            class="w-16 h-16 rounded bg-gray-50 border border-gray-200 object-contain">

                        <div class="flex-1">
                            <input type="file" name="logo" class="block w-full text-sm text-gray-700">
                            <p class="text-xs text-gray-500 mt-1">
                                PNG/JPG/WebP. Max 2MB. Uploading a new logo will replace the old one.
                            </p>
                        </div>
                    </div>
                </div>

                {{-- Office Address --}}
                <div class="mb-6">
                    <label class="block font-semibold text-gray-900 mb-2">Official Office Address</label>
                    <textarea name="office_address" rows="5"
                        class="w-full border border-gray-200 rounded-lg p-3 focus:outline-none focus:ring-2 focus:ring-blue-300"
                        placeholder="Enter the official office address used on invoices, receipts, and reports...">{{ old('office_address', $settings->office_address) }}</textarea>

                    <p class="text-xs text-gray-500 mt-1">
                        This is separate from location addresses and will be used on official documents generated by Pulze.
                    </p>
                </div>

                <button type="submit"
                    class="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-5 py-2 rounded-lg transition">
                    <i class="ph ph-floppy-disk"></i>
                    Save Settings
                </button>
            </form>
        </div>
    </div>
@endsection